### ISSUE TITLE
Migrate the configuration management page from confluence to github

### ISSUE THREAD

**Issue by Justus-at-Tazama** [frmscoe/docs#22]

**Comment by Justus-at-Tazama** [comment]
Check the way that the references are captured and select an approach

**Comment by Sandy-at-Tazama** [comment]
Fixed references

@Justus-at-Tazama Unable to edit https://frmscoe.atlassian.net/wiki/spaces/FRMS/pages/76906497/Configuration+management to show that it has moved to GitHub.  Not sure why, I'm able to edit other pages

**Comment by Sandy-at-Tazama** [comment]
Confluence page updated

**Comment by Sandy-at-Tazama** [comment]
Confluence page has been migrated.
