### ISSUE TITLE
Tazama Core Processors diagram - CADProc ref - readme.md

### ISSUE THREAD

**Issue by Sandy-Labuschagne** [frmscoe/docs#4]
The Tazama Core Processors diagram on Readme.md references CADProc in step 5 of Typology processor.  Change to "Transaction Aggregation" (aligned to diagram) or TADProc (used elsewhere)

https://github.com/frmscoe/docs/blob/main/README.md

![Tazama Core Processors](/images/tazama-core-components.png)

![image](https://github.com/frmscoe/docs/assets/142333955/a6faf537-9285-4854-bf1c-bd2594aa6fea)

**Comment by Justus-at-Tazama** [comment]
Updated
